[project]
name = "docs"
version = "0.1.0"
description = "OpusReader developer documentation build tooling"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "breathe>=4.36.0",
    "exhale>=0.3.7",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
]
