name: Deploy Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - run: pip install mkdocs-material mike
      
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Deploy latest docs (main)
        if: github.ref == 'refs/heads/main'
        run: |
          mike deploy --push --update-aliases latest
          mike set-default --push latest
      
      - name: Deploy versioned docs (tags)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          mike deploy --push --update-aliases $VERSION latest
          mike set-default --push latest
